# Generated by Django 4.1.4 on 2023-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='text',
            field=models.TextField(default='Enter text'),
            preserve_default=False,
        ),
    ]
